spring:
  application:
    name: admin
  freemarker:
    charset: utf-8
    settings:
      date_format : yyyy-MM-dd
      time_format : HH:mm:ss
      datetime_format : yyyy-MM-dd HH:mm:ss
      boolean_format : true,false
      number_format: 0.######
      whitespace_stripping : true
    suffix: .ftl
    content-type: text/html
    request-context-attribute: tt
  session:
    store-type: none
  datasource: #数据库
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.15.105.103/roow?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    password: 123456
    username: root
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 50
      max-wait: 6000
      time-between-connect-error-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
  cache:
    ehcache:
      config: ehcache.xml



server:
  port: 8001
tr:
  session:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: 123456
      timeout: 6000
  shiro:
    cache: ehcache
  captcha:
    random-word: abcdefghijkmnpqrstuvwxyz0123456789
    b: 200 # blue
    r: 100 # red
    g: 120  # green
    max-accepted-word-length: 5
    min-accepted-word-length: 5
mybatis:
  #config-location: classpath:/mybatis-config.xml
  executor-type: simple
  mapper-locations: classpath*:/mapper/**/*Dao.xml
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql






